version: '3.8'

services:

  symfony-example-database:
    container_name: symfony-example-database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/testing-db.sql:/docker-entrypoint-initdb.d/testing-db.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'
    networks:
      - example_network

  symfony-example-php:
    container_name: symfony-example-php
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    ports:
      - '9000:9000'
    depends_on:
      - symfony-example-database
    volumes:
      - .:/var/www/html
      - ./docker/php/ini/php.ini:/usr/local/etc/php/conf.d/custom_php.ini
    networks:
      - example_network

  symfony-example-nginx:
    container_name: symfony-example-nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites:/etc/nginx/sites-available
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - symfony-example-php
      - symfony-example-database
    networks:
      - example_network

networks:
  example_network: